name: Fable Factory Films
favicon: null
layout_spectrum: 0.66458
typography_spectrum: 0.48707
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b9b9b9'
    - '#000000'
    - '#8d8d8d'
    - '#ffffff'
    - '#737373'
  brandStrength: 1
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
