name: Fable Factory Films
favicon: null
layout_spectrum: 0.35858
typography_spectrum: 0.48707
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff4949'
    - '#e5dd4e'
    - '#308250'
    - '#ffffff'
    - '#3e2e55'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
