name: Fable Factory Films
favicon: null
layout_spectrum: 0.07354
typography_spectrum: 0.48707
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cc6462'
    - '#3d7799'
    - '#a7ffc6'
    - '#90b8cc'
    - '#090b0c'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
