name: Fable Factory Films
favicon: null
layout_spectrum: 0.35858
typography_spectrum: 0.48707
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090907'
    - '#42413c'
    - '#fefefc'
    - '#998550'
    - '#c2ab68'
  brandStrength: 0.9375
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
