name: Fable Factory Films
favicon: null
layout_spectrum: 0.35858
typography_spectrum: 0.48707
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#e2e2e2'
    - '#2c2c2c'
    - '#767676'
    - '#b4b4b4'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
